"""Stages 4-6 (code only, no model calls):
  group  - stable issue membership for completed complaint/cancellation records
  rank   - priority_score = severity_sum (= complaint_count x mean_severity), ties by issue_id
  memo   - deterministic draft memo + claims.csv from saved aggregates

Grouping v1 is one issue per topic (ISS-<topic>). A model-suggested sub-issue split is a later step;
whatever mapping is accepted gets saved so reranking never needs a model.
"""

import csv
import time
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

from .common import write_json
from .enrich import latest_records

GROUPING_VERSION = "group-topic-v1"


def mean6(total, n):
    return str((Decimal(total) / Decimal(n)).quantize(Decimal("0.000001"), rounding=ROUND_HALF_UP))


def group(out_dir):
    recs = latest_records(out_dir)
    membership = sorted((f"ISS-{r['topic']}", rid) for rid, r in recs.items()
                        if r["status"] == "completed" and r["intent"] in ("complaint", "cancellation"))
    path = Path(out_dir) / "membership.csv"
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["issue_id", "review_id"])
        w.writerows(membership)
    return membership


def rank(out_dir):
    """Recompute ranking from saved membership.csv + results.jsonl only."""
    out_dir = Path(out_dir)
    recs = latest_records(out_dir)
    agg = {}
    with (out_dir / "membership.csv").open(encoding="utf-8") as f:
        for row in csv.DictReader(f):
            a = agg.setdefault(row["issue_id"], [0, 0])
            a[0] += 1
            a[1] += recs[row["review_id"]]["severity"]
    ordered = sorted(agg.items(), key=lambda kv: (-kv[1][1], kv[0]))
    rows = [{"rank": i, "issue_id": iid, "complaint_count": n, "severity_sum": s,
             "mean_severity": mean6(s, n), "priority_score": s} for i, (iid, (n, s)) in enumerate(ordered, 1)]
    with (out_dir / "ranking.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]) if rows else ["rank", "issue_id", "complaint_count",
                                                                     "severity_sum", "mean_severity", "priority_score"])
        w.writeheader()
        w.writerows(rows)
    return rows


def memo(out_dir, top_n=None):
    """Draft memo from aggregates only. Every number comes from ranking.csv and is listed in claims.csv."""
    out_dir = Path(out_dir)
    with (out_dir / "ranking.csv").open(encoding="utf-8") as f:
        ranking = list(csv.DictReader(f))
    recs = latest_records(out_dir)
    total = len(recs)
    completed = sum(r["status"] == "completed" for r in recs.values())
    claims, lines = [], [f"# Draft priority memo ({GROUPING_VERSION})", "",
                         f"Scope: {total} reviews in this run, {completed} completed classifications. "
                         "Self-selected public reviews; cancellation language is stated intent, not observed churn.", ""]
    # A claim per metric for EVERY ranked issue: the memo role may discuss any of them, and each
    # material number it uses must have a claim_id to cite.
    for r in ranking[:top_n] if top_n else ranking:
        for metric in ("complaint_count", "mean_severity", "priority_score"):
            claims.append({"claim_id": f"C{len(claims) + 1}", "issue_id": r["issue_id"], "metric": metric, "value": r[metric]})
        ids = [c["claim_id"] for c in claims[-3:]]
        examples = sorted(rid for rid, x in recs.items() if x["status"] == "completed"
                          and f"ISS-{x['topic']}" == r["issue_id"] and x["intent"] in ("complaint", "cancellation")
                          and x["severity"] >= 3)[:3]
        lines.append(f"- Rank {r['rank']}: **{r['issue_id']}**, {r['complaint_count']} complaints, mean severity "
                     f"{r['mean_severity']}, priority {r['priority_score']} [{', '.join(ids)}]. Example review IDs: "
                     f"{', '.join(examples) or 'none at severity >= 3'}")
    lines += ["", "_Draft generated by code from saved aggregates (no model call). The final memo role will "
                  "receive only this ranking and a bounded evidence pack._"]
    (out_dir / "memo.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    with (out_dir / "claims.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["claim_id", "issue_id", "metric", "value"])
        w.writeheader()
        w.writerows(claims)
    return claims


def run_downstream(out_dir):
    t = {}
    t0 = time.monotonic(); m = group(out_dir); t["group_s"] = round(time.monotonic() - t0, 4)
    t0 = time.monotonic(); r = rank(out_dir); t["rank_s"] = round(time.monotonic() - t0, 4)
    t0 = time.monotonic(); c = memo(out_dir); t["memo_s"] = round(time.monotonic() - t0, 4)
    write_json(Path(out_dir) / "downstream_summary.json", {"grouping": GROUPING_VERSION, "memberships": len(m),
                                                           "issues": len(r), "claims": len(c), **t, "model_calls": 0})
    return t
